INSERT INTO `person` (`person_name`,`person_firstname`,`person_nickname`,`person_birthdate`,`person_deathdate`,`person_gender`,`person_description`,`person_country`,`person_language`,`person_occupations`,`person_nativename`,`person_external_id`) VALUES ('','Héraclius','l\'Ancien','','612','Homme','Officier supérieur de l\'armée de l\'empereur Maurice.','Empire Byzantin','','officier','','Q181690');
INSERT INTO `person` (`person_name`,`person_firstname`,`person_nickname`,`person_birthdate`,`person_deathdate`,`person_gender`,`person_description`,`person_country`,`person_language`,`person_occupations`,`person_nativename`,`person_external_id`) VALUES ('','Epiphania ','','56787','','Femme','Epouse de Héraclius l\'Ancien et mère de l\'empereur Heraclius (selon Cawley, Charles (2006–2016). \"Byzantium 395–1057\". Medieval Lands Project. Foundation for Medieval Genealogy. Retrieved 12 July 2016.)','Empire Byzantin','','','','Q30939233');
INSERT INTO `person` (`person_name`,`person_firstname`,`person_nickname`,`person_birthdate`,`person_deathdate`,`person_gender`,`person_description`,`person_country`,`person_language`,`person_occupations`,`person_nativename`,`person_external_id`) VALUES ('Fabia','Eudocia','','580','612','Femme','  Impératrice byzantine, première femme de l’empereur Héraclius','Empire Byzantin','','impératrice','','Q2619547');
INSERT INTO `person` (`person_name`,`person_firstname`,`person_nickname`,`person_birthdate`,`person_deathdate`,`person_gender`,`person_description`,`person_country`,`person_language`,`person_occupations`,`person_nativename`,`person_external_id`) VALUES ('Constantin IV','','Pogonat','v.650-34-12','685-ZER','Homme',' Souvent appelé indirectement Pogonat (Le Barbu)','Empire Byzantin','','','','Q41605');
INSERT INTO `person` (`person_name`,`person_firstname`,`person_nickname`,`person_birthdate`,`person_deathdate`,`person_gender`,`person_description`,`person_country`,`person_language`,`person_occupations`,`person_nativename`,`person_external_id`) VALUES ('Justinien II','','Rhinotmetus','','711','Homme',' Connu sous le surnom de Nez Coupé. Mort décapité.','Empire Byzantin','','','Ιουστινιανός Β (grec)','Q42021');
INSERT INTO `person` (`person_name`,`person_firstname`,`person_nickname`,`person_birthdate`,`person_deathdate`,`person_gender`,`person_description`,`person_country`,`person_language`,`person_occupations`,`person_nativename`,`person_external_id`) VALUES ('Héraclius Ier',' ',' ','575','641','Homme','Empereur romain d\'Orient de 610 à 641. Il est le fondateur de la dynastie des Héraclides.','Empire Byzantin','','empereur','Flavius Heraclius Augustus (Latin)','Q41852');
INSERT INTO `person` (`person_name`,`person_firstname`,`person_nickname`,`person_birthdate`,`person_deathdate`,`person_gender`,`person_description`,`person_country`,`person_language`,`person_occupations`,`person_nativename`,`person_external_id`) VALUES ('Constant II','','','','15-09-668','Homme','  Empereur byzantin de 641 à 668.','Empire Byzantin','','','','Q41613');
INSERT INTO `person` (`person_name`,`person_firstname`,`person_nickname`,`person_birthdate`,`person_deathdate`,`person_gender`,`person_description`,`person_country`,`person_language`,`person_occupations`,`person_nativename`,`person_external_id`) VALUES ('Constantin III','','','03-05-612','345-34 56','Homme','Est brièvement empereur byzantin de 12 février à 24/25 mai 641. Il appartient à la dynastie Héraclide','Empire Byzantin','','empereur','','Q41615');
INSERT INTO `person` (`person_name`,`person_firstname`,`person_nickname`,`person_birthdate`,`person_deathdate`,`person_gender`,`person_description`,`person_country`,`person_language`,`person_occupations`,`person_nativename`,`person_external_id`) VALUES ('','Gregoria Anastasia','','7 siècle','870','Femme','L\'épouse de l\'empereur byzantin Constantin III. À la mort de celui-ci, la régence de son fils Constant II fut officiellement confiée au patriarche Paul II de Constantinople. Sa participation notable à la régence n\'est pas mentionnée dans les sources byzantines','Empire Byzantin','','impératrice','','Q273871');
INSERT INTO `person` (`person_name`,`person_firstname`,`person_nickname`,`person_birthdate`,`person_deathdate`,`person_gender`,`person_description`,`person_country`,`person_language`,`person_occupations`,`person_nativename`,`person_external_id`) VALUES ('Constantin IV','','Pogonat','652','10 July 685','Homme','Souvent appelé incorrectement Pogonat, c\'est-à-dire « le Barbu », en confusion avec son père1, fils aîné de Constant II et de l\'impératrice Fausta, coempereur à partir de 654 puis empereur byzantin de septembre 668 à sa mort.','Empire Byzantin','grec','empereur','Constantinos','Q41605');


INSERT INTO `relation_type` (`relation_type_name`,`relation_type_code`,`relation_type_first_snap`,`relation_type_second_snap`,`relation_type_third_snap`,`relation_type_fourth_snap`) VALUES ('tante de','#AuntOf','#Bond','#ExtendedFamilyOf','#SiblingOfParentOf','');
INSERT INTO `relation_type` (`relation_type_name`,`relation_type_code`,`relation_type_first_snap`,`relation_type_second_snap`,`relation_type_third_snap`,`relation_type_fourth_snap`) VALUES ('oncle de','#UncleOf','#Bond','#ExtendedFamilyOf','#SiblingOfParentOf','');
INSERT INTO `relation_type` (`relation_type_name`,`relation_type_code`,`relation_type_first_snap`,`relation_type_second_snap`,`relation_type_third_snap`,`relation_type_fourth_snap`) VALUES ('neveu de','#NephewOf','#Bond','#ExtendedFamilyOf','#ChildOfSiblingOf','');
INSERT INTO `relation_type` (`relation_type_name`,`relation_type_code`,`relation_type_first_snap`,`relation_type_second_snap`,`relation_type_third_snap`,`relation_type_fourth_snap`) VALUES ('nièce de','#NieceOf','#Bond','#ExtendedFamilyOf','#ChildOfSiblingOf','');
INSERT INTO `relation_type` (`relation_type_name`,`relation_type_code`,`relation_type_first_snap`,`relation_type_second_snap`,`relation_type_third_snap`,`relation_type_fourth_snap`) VALUES ('cousine ou cousin de','#CousinOf','#Bond','#ExtendedFamilyOf','','');
INSERT INTO `relation_type` (`relation_type_name`,`relation_type_code`,`relation_type_first_snap`,`relation_type_second_snap`,`relation_type_third_snap`,`relation_type_fourth_snap`) VALUES ('petite-fille de','#GranddaughterOf','#Bond','#ExtendedFamilyOf','#DescendentOf','#GrandchildOf');
INSERT INTO `relation_type` (`relation_type_name`,`relation_type_code`,`relation_type_first_snap`,`relation_type_second_snap`,`relation_type_third_snap`,`relation_type_fourth_snap`) VALUES ('petit-fils de','#GrandsonOf','#Bond','#ExtendedFamilyOf','#DescendentOf','#GrandchildOf');
INSERT INTO `relation_type` (`relation_type_name`,`relation_type_code`,`relation_type_first_snap`,`relation_type_second_snap`,`relation_type_third_snap`,`relation_type_fourth_snap`) VALUES ('grand-père de','#GrandfatherOf','#Bond','#ExtendedFamilyOf','#AncestorOf','#GrandparentOf');
INSERT INTO `relation_type` (`relation_type_name`,`relation_type_code`,`relation_type_first_snap`,`relation_type_second_snap`,`relation_type_third_snap`,`relation_type_fourth_snap`) VALUES ('grand-mère de','#GrandmotherOf','#Bond','#ExtendedFamilyOf','#AncestorOf','#GrandparentOf');
INSERT INTO `relation_type` (`relation_type_name`,`relation_type_code`,`relation_type_first_snap`,`relation_type_second_snap`,`relation_type_third_snap`,`relation_type_fourth_snap`) VALUES ('arrière-grand-père de','#GreatGrandfatherOf','#Bond','#ExtendedFamilyOf','#AncestorOf','#GreatGrandparentOf');
INSERT INTO `relation_type` (`relation_type_name`,`relation_type_code`,`relation_type_first_snap`,`relation_type_second_snap`,`relation_type_third_snap`,`relation_type_fourth_snap`) VALUES ('arrière-grand-mère de','#GreatGrandmotherOf','#Bond','#ExtendedFamilyOf','#AncestorOf','#GreatGrandparentOf');
INSERT INTO `relation_type` (`relation_type_name`,`relation_type_code`,`relation_type_first_snap`,`relation_type_second_snap`,`relation_type_third_snap`,`relation_type_fourth_snap`) VALUES ('frère de','#BrotherOf','#Bond','#HereditaryFamilyOf','#SiblingOf','');
INSERT INTO `relation_type` (`relation_type_name`,`relation_type_code`,`relation_type_first_snap`,`relation_type_second_snap`,`relation_type_third_snap`,`relation_type_fourth_snap`) VALUES ('soeur de','#SisterOf','#Bond','#HereditaryFamilyOf','#SiblingOf','');
INSERT INTO `relation_type` (`relation_type_name`,`relation_type_code`,`relation_type_first_snap`,`relation_type_second_snap`,`relation_type_third_snap`,`relation_type_fourth_snap`) VALUES ('fille de','#DaughterOf','#Bond','#HereditaryFamilyOf','#ParentOf','');
INSERT INTO `relation_type` (`relation_type_name`,`relation_type_code`,`relation_type_first_snap`,`relation_type_second_snap`,`relation_type_third_snap`,`relation_type_fourth_snap`) VALUES ('fils de','#SonOf','#Bond','#HereditaryFamilyOf','#ParentOf','');
INSERT INTO `relation_type` (`relation_type_name`,`relation_type_code`,`relation_type_first_snap`,`relation_type_second_snap`,`relation_type_third_snap`,`relation_type_fourth_snap`) VALUES ('mère de','#MotherOf','#Bond','#HereditaryFamilyOf','#ParentOf','');
INSERT INTO `relation_type` (`relation_type_name`,`relation_type_code`,`relation_type_first_snap`,`relation_type_second_snap`,`relation_type_third_snap`,`relation_type_fourth_snap`) VALUES ('père de','#FatherOf','#Bond','#HereditaryFamilyOf','#ParentOf','');
INSERT INTO `relation_type` (`relation_type_name`,`relation_type_code`,`relation_type_first_snap`,`relation_type_second_snap`,`relation_type_third_snap`,`relation_type_fourth_snap`) VALUES ('esclave de','#SlaveOf','#Bond','#ExtendedHouseholdOf','','');
INSERT INTO `relation_type` (`relation_type_name`,`relation_type_code`,`relation_type_first_snap`,`relation_type_second_snap`,`relation_type_third_snap`,`relation_type_fourth_snap`) VALUES ('esclave libéré de','#FreedSlaveOf','#Bond','#ExtendedHouseholdOf','','');
INSERT INTO `relation_type` (`relation_type_name`,`relation_type_code`,`relation_type_first_snap`,`relation_type_second_snap`,`relation_type_third_snap`,`relation_type_fourth_snap`) VALUES ('homme libéré de','#FreedmanOf','#Bond','#ExtendedHouseholdOf','','');
INSERT INTO `relation_type` (`relation_type_name`,`relation_type_code`,`relation_type_first_snap`,`relation_type_second_snap`,`relation_type_third_snap`,`relation_type_fourth_snap`) VALUES ('femme libérée de','#FreedwomanOf','#Bond','#ExtendedHouseholdOf','','');
INSERT INTO `relation_type` (`relation_type_name`,`relation_type_code`,`relation_type_first_snap`,`relation_type_second_snap`,`relation_type_third_snap`,`relation_type_fourth_snap`) VALUES ('relation intime occasionnelle avec','#CasualIntimateRelationshipWith','#Bond','#IntimateRelationshipWith','','');
INSERT INTO `relation_type` (`relation_type_name`,`relation_type_code`,`relation_type_first_snap`,`relation_type_second_snap`,`relation_type_third_snap`,`relation_type_fourth_snap`) VALUES ('relation intime sérieuse avec','#SeriousIntimateRelationshipWith','#Bond','#IntimateRelationshipWith','','');
INSERT INTO `relation_type` (`relation_type_name`,`relation_type_code`,`relation_type_first_snap`,`relation_type_second_snap`,`relation_type_third_snap`,`relation_type_fourth_snap`) VALUES ('ennemi de','#EnmityFor','#Bond','','','');
INSERT INTO `relation_type` (`relation_type_name`,`relation_type_code`,`relation_type_first_snap`,`relation_type_second_snap`,`relation_type_third_snap`,`relation_type_fourth_snap`) VALUES ('ami avec','#FriendshipFor','#Bond','#AllianceWith','','');


INSERT INTO `link` (`link_person1_id`,`link_person2_id`,`link_relation_type_id`) VALUES (10,7,15);
INSERT INTO `link` (`link_person1_id`,`link_person2_id`,`link_relation_type_id`) VALUES (7,10,17);
INSERT INTO `link` (`link_person1_id`,`link_person2_id`,`link_relation_type_id`) VALUES (1,2,23);
INSERT INTO `link` (`link_person1_id`,`link_person2_id`,`link_relation_type_id`) VALUES (2,1,23);
INSERT INTO `link` (`link_person1_id`,`link_person2_id`,`link_relation_type_id`) VALUES (1,6,17);
INSERT INTO `link` (`link_person1_id`,`link_person2_id`,`link_relation_type_id`) VALUES (2,6,16);
INSERT INTO `link` (`link_person1_id`,`link_person2_id`,`link_relation_type_id`) VALUES (6,1,15);
INSERT INTO `link` (`link_person1_id`,`link_person2_id`,`link_relation_type_id`) VALUES (6,2,15);
